os: linux
dist: bionic
language: python
sudo: true

python:
  - "3.8"

before_install:
  - sudo apt update
  - sudo apt install python3-pip
  - python -m pip install --upgrade pip

install:
  - pip install -r requirements.txt

script:
  - python -m Discord_URL.py
